from enum import Enum

class ENTITY_STATUS(Enum):
  ENTITY_STATUS_DISABLED=0
  ENTITY_STATUS_DYING=1
  ENTITY_STATUS_FALLING=2
  ENTITY_STATUS_DESTROYING=3
  ENTITY_STATUS_INIT=4
  ENTITY_STATUS_ACTIVE=5
  ENTITY_STATUS_STUNNED=6
  ENTITY_STATUS_LIFTED=7
  ENTITY_STATUS_THROWN=8

class INVENTORY(Enum):
  INVENTORY_EMPTY=0x00
  INVENTORY_SWORD=0x01
  INVENTORY_BOMBS=0x02
  INVENTORY_POWER_BRACELET=0x03
  INVENTORY_SHIELD=0x04
  INVENTORY_BOW=0x05
  INVENTORY_HOOKSHOT=0x06
  INVENTORY_MAGIC_ROD=0x07
  INVENTORY_PEGASUS_BOOTS=0x08
  INVENTORY_OCARINA=0x09
  INVENTORY_ROCS_FEATHER=0x0A
  INVENTORY_SHOVEL=0x0B
  INVENTORY_MAGIC_POWDER=0x0C
  INVENTORY_BOOMERANG=0x0D

class STAIRCASE(Enum):
  STAIRCASE_NONE=0
  STAIRCASE_INACTIVE=1
  STAIRCASE_ACTIVE=2